/**
 * Generate the SQLite dev schema from the canonical Postgres one.
 *
 * Prisma requires a literal `provider`, so a schema cannot serve both databases
 * from one file. The usual fix is to hand-maintain a second schema, which drifts
 * the moment someone edits one and forgets the other.
 *
 * Instead this rewrites the canonical schema mechanically, and fails loudly if
 * it meets something it does not know how to translate. Two rules so far:
 *
 *   1. the datasource provider
 *   2. Postgres-only native type attributes (`@db.Decimal(20, 6)`), which Prisma
 *      rejects outright on SQLite
 *
 * Every model, field, index and relation stays identical by construction. Prisma
 * 6.19 accepts `enum` and bare `Decimal` on SQLite, so those need no translation.
 *
 * Generated file is gitignored; regenerate with `pnpm db:dev`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const prismaDir = join(here, "..", "apps", "web", "prisma");
const source = join(prismaDir, "schema.prisma");
const target = join(prismaDir, "schema.dev.prisma");

const schema = readFileSync(source, "utf8");

// Only the provider line inside the datasource block, not any other occurrence.
const patched = schema.replace(
  /(datasource\s+db\s*\{[^}]*?provider\s*=\s*)"postgresql"/,
  '$1"sqlite"'
);

if (patched === schema) {
  console.error(
    "Could not find `provider = \"postgresql\"` in the datasource block of\n" +
      `  ${source}\n` +
      "The dev schema was not written. Update the pattern in scripts/dev-schema.mjs."
  );
  process.exit(1);
}

// Postgres-native type attributes. Bare `Decimal` works on both databases, but
// the moment a precision is pinned — `@db.Decimal(20, 6)` — the attribute is
// Postgres-only and SQLite refuses to parse it. Dropping it loses nothing that
// matters here: SQLite stores decimals as NUMERIC (float64), which is exact for
// every integer up to 2^53, and a 6-decimal USDC amount tops out around 10^13.
//
// Only attributes known to be safe to drop are stripped. An unrecognised one is
// a hard error rather than a silent omission, because the failure it would
// otherwise cause lands much later and points somewhere else entirely: the
// generated schema simply would not push.
const nativeAttrs = [...patched.matchAll(/@db\.(\w+)/g)].map((m) => m[1]);
const unhandled = [...new Set(nativeAttrs)].filter((name) => name !== "Decimal");
if (unhandled.length > 0) {
  console.error(
    `Unhandled Postgres native type attribute(s): ${unhandled.join(", ")}\n` +
      "Add a translation rule in scripts/dev-schema.mjs, or drop the attribute\n" +
      `from ${source} if SQLite can express the same thing.`
  );
  process.exit(1);
}

const translated = patched.replace(/\s+@db\.Decimal(?:\([^)]*\))?/g, "");

writeFileSync(
  target,
  `// GENERATED by scripts/dev-schema.mjs — do not edit.\n` +
    `// Source of truth: schema.prisma. Differences: the datasource provider and\n` +
    `// Postgres-only native type attributes, both stripped mechanically.\n\n` +
    translated
);

console.log(`wrote ${target.replace(join(here, ".."), ".")}`);
